### ISSUE TITLE
Support non cloud servers

### ISSUE THREAD

**Issue by ofir-petrushka** [GoogleCloudPlatform/stackdriver-ansible-role#1]
Support non cloud servers, this is the hack I have used, probably there is a better way... (identify when there is no cloud id found and only then use the gen...)
  command: /opt/stackdriver/stack-config --api-key {{ stackdriver_api_key }} --genhostid

**Comment by rimey** [comment]
Non-cloud servers is an important use case that I haven't tried.

Invoking `stack-config` as you described sounds like a practical solution. Is it working for you?

If you are blocked, or if you might want to put together a pull request, please let me know.

**Comment by ofir-rounds** [comment]
It is working for me (got it from support, there is some beta guild
mentioning it), I just don't know it well to know if that will damage cloud
nodes and what the flow should be. Without it if fails to start...
I'm a 1st time user just testing the system out, my 1st install.

**Comment by rimey** [comment]
It looks like `stack-config --genhostid` will fail with an error if it is run on a cloud node. There doesn't seem to be a way to run it so that it generates a random host ID if and only if it is not running on a cloud node. So you would only want to have Ansible execute `stack-config` on a non-cloud node.

If this is an adequate workaround for you, perhaps no change to the code is necessary. But if you end up blocked, just say so, and we'll work something out.
